# Generated by Django 6.1.1 on 2026-09-24 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('project_number', models.CharField(default='01', help_text='e.g. 01, 02', max_length=10)),
                ('category', models.CharField(help_text='e.g. AI & REST APIs, Computer Vision, Backend System', max_length=100)),
                ('year', models.CharField(default='2026', max_length=20)),
                ('short_description', models.TextField(help_text='One or two crisp sentences for cards and summaries')),
                ('description', models.TextField(help_text='In-depth project case study and overview')),
                ('featured', models.BooleanField(default=True)),
                ('github_url', models.URLField(blank=True, default='', help_text='GitHub repository URL')),
                ('live_url', models.URLField(blank=True, default='', help_text='Live demo or swagger endpoint URL')),
                ('architecture_description', models.TextField(blank=True, help_text='Detailed engineering architecture breakdown')),
                ('architecture_flow', models.TextField(blank=True, help_text='Semicolon or newline separated pipeline stages')),
                ('challenge', models.TextField(blank=True, help_text='Real technical challenge encountered')),
                ('solution', models.TextField(blank=True, help_text='Exact engineered solution and design pattern used')),
                ('learning', models.TextField(blank=True, help_text='Key takeaways and architectural insights')),
                ('key_features', models.TextField(blank=True, help_text='Key technical features, newline separated')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/thumbnails/')),
                ('thumbnail_svg_code', models.TextField(blank=True, help_text='Inline technical SVG visual or schematic diagram')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('category', models.CharField(choices=[('BACKEND', 'Backend'), ('DATABASE', 'Database'), ('TOOLS', 'Tools & Environment'), ('AI_CV', 'AI & Computer Vision'), ('DEVOPS', 'DevOps & Deployment')], default='BACKEND', max_length=30)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name or SVG descriptor', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Concise engineering role of this tech', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/gallery/')),
                ('image_url', models.CharField(blank=True, help_text='Fallback external URL or static path', max_length=500)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.technology'),
        ),
    ]
