# Generated by Django 6.1.1 on 2026-09-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='Organization, company or independent project scope', max_length=200)),
                ('role', models.CharField(help_text='Role e.g. Python Backend Developer / AI-CV Intern', max_length=200)),
                ('location', models.CharField(default='Surat, Gujarat, India', max_length=150)),
                ('description', models.TextField(help_text='Overview of responsibilities and technical engineering scope')),
                ('highlights', models.TextField(blank=True, help_text='Newline-separated bullet points of technical achievements')),
                ('start_date', models.CharField(help_text='e.g. Jan 2024', max_length=50)),
                ('end_date', models.CharField(default='Present', help_text='e.g. Present or June 2024', max_length=50)),
                ('is_current', models.BooleanField(default=False)),
                ('experience_type', models.CharField(choices=[('INTERNSHIP', 'Internship'), ('PROFESSIONAL_PROJECT', 'Professional Project'), ('PERSONAL_PROJECT', 'Personal Project')], default='PERSONAL_PROJECT', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProfileConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Ujval Thakor', max_length=100)),
                ('primary_title', models.CharField(default='Backend Developer', max_length=100)),
                ('secondary_title', models.CharField(default='Python • Django • REST APIs • AI/ML', max_length=150)),
                ('short_positioning', models.TextField(default='I build reliable backend systems, APIs, automation tools, and AI-powered applications.')),
                ('current_status', models.CharField(default='B.Tech Computer Engineering student with hands-on Python and Django development experience.', max_length=200)),
                ('location', models.CharField(default='Surat, Gujarat, India', max_length=100)),
                ('available_for_work', models.BooleanField(default=True)),
                ('github_url', models.URLField(blank=True, default='https://github.com/ujvalthakor')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/in/ujvalthakor')),
                ('email', models.EmailField(default='ujvalthakor.dev@gmail.com', max_length=254)),
                ('hero_statement_line1', models.CharField(default='BACKEND', max_length=100)),
                ('hero_statement_line2', models.CharField(default='ENGINEER', max_length=100)),
                ('hero_statement_line3', models.CharField(default='who builds', max_length=100)),
                ('hero_statement_line4', models.CharField(default='systems that', max_length=100)),
                ('hero_statement_line5', models.CharField(default='actually work.', max_length=100)),
                ('about_editorial_heading', models.TextField(default='I BUILD THE\nSYSTEM BEHIND\nTHE EXPERIENCE.')),
                ('about_editorial_text', models.TextField(default='I’m a B.Tech Computer Engineering student and backend developer focused on Python and Django. I enjoy turning ideas into structured backend systems — from REST APIs and database architecture to authentication, automation and AI-powered applications.')),
            ],
            options={
                'verbose_name': 'Profile Configuration',
                'verbose_name_plural': 'Profile Configuration',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ujval Thakor — Backend Developer Resume', max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('summary', models.TextField(blank=True, default='B.Tech Computer Engineering student with hands-on Python and Django development experience. Skilled in REST APIs, MySQL, PostgreSQL, Redis, Docker, OpenCV, and AI integration.')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one resume should be active at a time')),
                ('download_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('BACKEND', 'Backend & Core'), ('DATABASE', 'Database & Caching'), ('ARCHITECTURE', 'System Architecture & APIs'), ('AI_CV', 'AI & Computer Vision'), ('DEVOPS', 'DevOps & Tooling')], default='BACKEND', max_length=30)),
                ('badge_label', models.CharField(blank=True, help_text='e.g. Production Ready, Core Strength, Hands-on', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
