# Generated by Django 6.1.1 on 2026-09-28 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UJVAL.AI Agent', max_length=100)),
                ('headline', models.CharField(default='Portfolio Sales & Engineering Assistant', max_length=255)),
                ('active_provider', models.CharField(choices=[('auto', 'Auto-Detect (Use Available API Key)'), ('gemini', 'Google Gemini (Native)'), ('openai', 'OpenAI (GPT-4o / GPT-4o-mini)'), ('groq', 'Groq (Llama 3.1)'), ('grounded', 'Deterministic Grounded Engine (Offline/Safe)')], default='auto', max_length=30)),
                ('hot_lead_threshold', models.IntegerField(default=75, help_text='Minimum score to trigger immediate notification')),
                ('notification_email', models.EmailField(default='ujvalthakor14@gmail.com', max_length=254)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('pricing_disclosed', models.BooleanField(default=False, help_text='Allow disclosing estimated pricing if configured')),
                ('pricing_notes', models.TextField(blank=True, default='Ujval provides custom quotes based on project specifications, timeline, and architectural requirements.')),
                ('custom_instructions', models.TextField(blank=True, help_text='Optional custom instructions to append to the system prompt.')),
            ],
            options={
                'verbose_name': 'Agent Configuration',
                'verbose_name_plural': 'Agent Configuration',
            },
        ),
        migrations.CreateModel(
            name='AvailabilityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available for Projects & Roles'), ('LIMITED', 'Limited Availability'), ('UNAVAILABLE', 'Currently Unavailable')], default='AVAILABLE', max_length=20)),
                ('headline', models.CharField(default='Available for selected backend, API, and AI engineering projects', max_length=255)),
                ('project_work', models.BooleanField(default=True, help_text='Open to freelance & contract projects')),
                ('freelance', models.BooleanField(default=True, help_text='Open to independent consulting')),
                ('full_time', models.BooleanField(default=True, help_text='Open to full-time engineering roles')),
                ('internship', models.BooleanField(default=False, help_text='Open to internship roles')),
                ('notes', models.TextField(blank=True, default='Focused on Python, Django, REST APIs, and Computer Vision / AI solutions.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Availability Status',
                'verbose_name_plural': 'Availability Status',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=120)),
                ('visitor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('qualified', 'Qualified Lead'), ('handoff', 'Human Handoff Requested'), ('closed', 'Closed')], default='active', max_length=30)),
                ('detected_intent', models.CharField(choices=[('general_visitor', 'General Visitor'), ('potential_client', 'Potential Client'), ('recruiter', 'Recruiter / Hiring Manager'), ('developer', 'Developer Peer'), ('student', 'Student / Learner')], default='general_visitor', max_length=50)),
                ('lead_score', models.IntegerField(default=0)),
                ('lead_temperature', models.CharField(choices=[('cold', 'Cold (Browsing)'), ('warm', 'Warm (Inquiring)'), ('hot', 'Hot (High Intent)')], default='cold', max_length=20)),
                ('handoff_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Conversation',
                'verbose_name_plural': 'AI Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('lead_type', models.CharField(choices=[('potential_client', 'Potential Client'), ('recruiter', 'Recruiter / Hiring Manager'), ('developer', 'Developer'), ('student', 'Student'), ('general_visitor', 'General Visitor')], default='potential_client', max_length=50)),
                ('intent', models.CharField(blank=True, help_text='Summarized visitor intent', max_length=255)),
                ('score', models.IntegerField(default=0, help_text='Calculated lead quality score (0 - 100)')),
                ('temperature', models.CharField(choices=[('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot 🔥')], default='cold', max_length=20)),
                ('requirements', models.TextField(blank=True, help_text='Problem statement / requirements')),
                ('project_type', models.CharField(blank=True, help_text='e.g. AI Vision, Django Backend, Automation', max_length=150)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('timeline', models.CharField(blank=True, max_length=100)),
                ('preferred_contact', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted / In Progress'), ('qualified', 'Qualified'), ('closed', 'Closed / Converted'), ('archived', 'Archived')], default='new', max_length=30)),
                ('notified', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='chatbot.conversation')),
            ],
            options={
                'verbose_name': 'Qualified Lead',
                'verbose_name_plural': 'Qualified Leads',
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email Notification'), ('web_push', 'Web Push'), ('mobile_push', 'Mobile Push'), ('dashboard', 'Admin Dashboard Alert')], default='email', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent Successfully'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('payload_preview', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chatbot.lead')),
            ],
            options={
                'verbose_name': 'Lead Notification',
                'verbose_name_plural': 'Lead Notifications',
                'ordering': ['-sent_at'],
            },
        ),
    ]
